### ISSUE TITLE
PlatformViews 似乎有bug

### ISSUE THREAD

**Issue by hidetag** [fluttify-project/amap_map_fluttify#127]
**插件版本**
`0.15.0+5a112a2`
**遇到bug的平台(Android/iOS)**
`Android`
**描述bug**
`手机显示地图界面，息屏后再打开`
**复现步骤**
`手机显示地图界面，息屏后解锁，Logcat 中无限报错，同时地图卡死，无法操作，但地图以外的其他操作不受影响`
**期望行为**

**截图**
`E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '_asList' was called on null.
    Receiver: null
    Tried calling: _asList()
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      AndroidMotionEvent._asList.<anonymous closure> (package:flutter/src/services/platform_views.dart:408:74)
    #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
    #3      ListIterable.toList (dart:_internal/iterable.dart:221:19)
    #4      AndroidMotionEvent._asList (package:flutter/src/services/platform_views.dart:408:85)
    #5      AndroidViewController.sendMotionEvent (package:flutter/src/services/platform_views.dart:615:15)
    #6      _MotionEventsDispatcher.dispatchPointerEvent (package:flutter/src/rendering/platform_view.dart:649:20)
    #7      _MotionEventsDispatcher.handlePointerEvent (package:flutter/src/rendering/platform_view.dart:577:5)
    #8      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:511:7)
    #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
    #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
    #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
    #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
    #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
    #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
    #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #19     _rootRunUnary (dart:async/zone.dart:1138:13)
    #20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #22     _invoke1 (dart:ui/hooks.dart:273:10)
    #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)`
**flutter doctor**
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)`

**Comment by hidetag** [comment]
补充日志，不知是否有帮助：
`2019-12-26 09:59:40.133 14057-14057/com.goldenridge.parkroveradmin E/WindowManager: BadTokenException or InvalidDisplayException, clean up.
2019-12-26 09:59:40.137 14057-14057/com.goldenridge.parkroveradmin E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.SecurityException: Neither user 10635 nor current process has android.permission.WAKE_LOCK.
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:886)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
        at android.app.Dialog.show(Dialog.java:344)
        at android.app.Presentation.show(Presentation.java:250)
        at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:150)
        at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:180)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:129)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:66)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:182)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:1906)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1934)
        at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4430)
        at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2188)
        at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2154)
2019-12-26 09:59:40.143 14057-14125/com.goldenridge.parkroveradmin E/flutter: [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
    PlatformException(error, Neither user 10635 nor current process has android.permission.WAKE_LOCK., null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
    <asynchronous suspension>
    #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:559:41)
    #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
    #4      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
    #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
    #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #8      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #10     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #12     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #14     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
    #15     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
    #16     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
    #17     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
    #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #22     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #39     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
    #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #41     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #43     RenderProxyBoxMixi`

**Comment by hidetag** [comment]
补充日志，不知是否有帮助：
`2019-12-26 09:59:40.133 14057-14057/com.goldenridge.parkroveradmin E/WindowManager: BadTokenException or InvalidDisplayException, clean up.
2019-12-26 09:59:40.137 14057-14057/com.goldenridge.parkroveradmin E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.SecurityException: Neither user 10635 nor current process has android.permission.WAKE_LOCK.
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:886)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
        at android.app.Dialog.show(Dialog.java:344)
        at android.app.Presentation.show(Presentation.java:250)
        at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:150)
        at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:180)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:129)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:66)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:182)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:1906)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1934)
        at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4430)
        at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2188)
        at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2154)
2019-12-26 09:59:40.143 14057-14125/com.goldenridge.parkroveradmin E/flutter: [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
    PlatformException(error, Neither user 10635 nor current process has android.permission.WAKE_LOCK., null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
    <asynchronous suspension>
    #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:559:41)
    #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
    #4      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
    #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
    #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #8      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #10     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #12     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #14     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
    #15     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
    #16     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
    #17     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
    #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #22     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    #39     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
    #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #41     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
    #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
    #43     RenderProxyBoxMixi`

**Comment by RyanYANG52** [comment]
我之前也遇到类似错误，我的问题应该是多线程操作controller导致的。多线程的时候，（比如一个是网络请求的callback一个是UI的操作）只是await应该还不够，我用https://pub.flutter-io.cn/packages/synchronized 给所有的controller操作加了lock。然后程序进入后台再进来就不报错了。你可以试试。

**Comment by hidetag** [comment]
@RyanYANG52 好的，我试试看，这个库我也导了的，就是用来加锁，地图这边倒没用，我先试试看，多谢

**Comment by hidetag** [comment]
@RyanYANG52 经过这几天发现没有出现过卡死的情况了，但白屏问题依然存在，而且出现概率依然居高不下:confused:
Duplicate of #128
