### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by hidetag** [fluttify-project/amap_map_fluttify#128]
**插件版本**
`0.15.0+5a112a2`
**遇到bug的平台(Android/iOS)**
`Android`
**描述bug**
`地图白屏`
**复现步骤**
`在真机上运行后，静置手机几秒，地图界面有概率会白屏，从接入开始至今，大约 30% 概率会突然白屏，此时不影响应用其他功能使用，未被阻塞，同时也能使用地图其他功能，例如获取当前位置经纬度的方法（controller.getLocation()）`
**期望行为**

**截图**
![Screenshot_2019-12-26-10-16-58-603_com goldenridg](https://user-images.githubusercontent.com/15097928/71453980-4f443000-27c9-11ea-8995-a14cbf63b1ad.jpg)

**flutter doctor**
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)`

**Comment by hidetag** [comment]
白屏后这次有些许日志，但不知道是否和白屏相关
增加日志如下：
`
java.lang.RuntimeException: getUniform: glError 1281
    at com.amap.api.mapcore.util.eq.a(GlesUtility.java:43)
    at com.amap.api.mapcore.util.dw$d.<init>(GlShaderManager.java:242)
    at com.amap.api.mapcore.util.dw.c(GlShaderManager.java:59)
    at com.amap.api.mapcore.util.dw.a(GlShaderManager.java:119)
    at com.amap.api.mapcore.util.c.u(AMapDelegateImp.java:5962)
    at com.amap.api.mapcore.util.aa.k(MapOverlayImageView.java:529)
    at com.amap.api.mapcore.util.aa.a(MapOverlayImageView.java:546)
    at com.amap.api.mapcore.util.aa.a(MapOverlayImageView.java:464)
    at com.amap.api.mapcore.util.aa.a(MapOverlayImageView.java:433)
    at com.amap.api.mapcore.util.c.afterDrawLabel(AMapDelegateImp.java:5306)
    at com.autonavi.ae.gmap.GLMapEngine.onMapRender(GLMapEngine.java:277)
    at com.autonavi.ae.gmap.GLMapEngine.nativeRenderAMap(Native Method)
    at com.autonavi.ae.gmap.GLMapEngine.renderAMap(GLMapEngine.java:1537)
    at com.amap.api.mapcore.util.c.drawFrame(AMapDelegateImp.java:2181)
    at com.autonavi.ae.gmap.GLMapRender.drawSingleFrame(GLMapRender.java:164)
    at com.autonavi.ae.gmap.GLMapRender.onDrawFrame(GLMapRender.java:179)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
`
以上是其一；
下面是其二，操作地图的时候抛出的异常：
`
java.lang.NullPointerException: Attempt to invoke virtual method 'android.location.Location com.amap.api.maps.AMap.getMyLocation()' on a null object reference
    at me.yohom.amap_map_fluttify.AmapMapFluttifyPlugin$1.lambda$new$2406(Unknown Source:60)
    at me.yohom.amap_map_fluttify.-$$Lambda$AmapMapFluttifyPlugin$1$f7JDgx_QjMwohFqox86B9oOqLzE.call(Unknown Source:0)
    at me.yohom.amap_map_fluttify.AmapMapFluttifyPlugin.onMethodCall(Unknown Source:16)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:336)
    at android.os.Looper.loop(Looper.java:182)
    at android.app.ActivityThread.main(ActivityThread.java:7523)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
`

**Comment by bentu-noodoe** [comment]
我這裡也是

**Comment by dsmjoy** [comment]
我这里白屏复现概率比较高, 不止30%了

**Comment by yohom** [comment]
白屏我之前也碰到过很多次，但是白屏的时候没有报错，所以很难排查，我一直怀疑是原生代码有报错。
刚才我用release模式运行example工程，去除hot reload/hot restart因素，试了很多次都没有再出现白屏，你们可以测试下release模式是否还能再复现这个bug。

**Comment by hidetag** [comment]
#200

**Comment by hidetag** [comment]
> 白屏我之前也碰到过很多次，但是白屏的时候没有报错，所以很难排查，我一直怀疑是原生代码有报错。
> 刚才我用release模式运行example工程，去除hot reload/hot restart因素，试了很多次都没有再出现白屏，你们可以测试下release模式是否还能再复现这个bug。

开发阶段热重载一直是关闭的，没有使用

**Comment by rongwei84n** [comment]
开发模式下滑动就很大几率白屏；尝试flutter build apk安装后，发现基本不会白屏，。

**Comment by hidetag** [comment]
debug 包几乎每次都会，release 偶尔也会，我是小米 8.

**Comment by yohom** [comment]
0.23以上版本，已经使用TextureMapView代替MapView，没有再出现白屏问题。
