### ISSUE TITLE
启动程序，第一次进入地图界面，不显示定位

### ISSUE THREAD

**Issue by houqinzhe** [fluttify-project/amap_map_fluttify#165]
**插件版本**
amap_map_fluttify: 0.17.11+69360c9
**遇到bug的平台(Android/iOS)**
iOS

**描述bug**
程序启动，第一次进入地图界面，调用定位，不会定位到当前位置。
返回之后再进入才会显示出定位的位置
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by k-dylan** [comment]
我也遇到这个问题了，使用的是小米6手机。在app安装后第一次打开，无法定位到当前位置，返回再次进入页面就显示了；
报错信息：
```
E/flutter (14295): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
E/flutter (14295): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (14295): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (14295): <asynchronous suspension>
E/flutter (14295): #2      com_amap_api_services_poisearch_PoiResult.getPois (package:amap_search_fluttify/src/android/com/amap/api/services/poisearch/PoiResult.g.dart:128:73)
E/flutter (14295): #3      _AndroidSearchListener.onPoiSearched (package:amap_search_fluttify/src/dart/amap_search.dart:1053:38)
E/flutter (14295): #4      com_amap_api_services_poisearch_PoiSearch.setOnPoiSearchListener.<anonymous closure> (package:amap_search_fluttify/src/android/com/amap/api/services/poisearch/PoiSearch.g.dart:77:21)
E/flutter (14295): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
E/flutter (14295): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
E/flutter (14295): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter (14295): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
E/flutter (14295): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (14295): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (14295): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (14295): #12     _invoke3 (dart:ui/hooks.dart:302:10)
E/flutter (14295): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
E/flutter (14295): 

```
