### ISSUE TITLE
MapView 设置中心点坐标 centerCoordinate 以及 AmapController 在 onMapCreated 出现奔溃

### ISSUE THREAD

**Issue by zoulu123** [fluttify-project/amap_map_fluttify#199]
MapView 设置中心点坐标 centerCoordinate 以及 AmapController 在 onMapCreated 出现奔溃
（我是想在进入页面初始化的时候设置我自己的地图中心点，发现每次都会奔溃，用的是你们 1.8.1 最新的 api，在 android 真机上跑的）
Process: com.example.rongcloud_im_plugin_example, PID: 21901
    java.lang.RuntimeException: Unbalanced drawPending/pendingDrawFinished calls
        at android.view.ViewRootImpl.pendingDrawFinished(ViewRootImpl.java:3303)
        at android.view.SurfaceView.notifyDrawFinished(SurfaceView.java:317)
        at android.view.SurfaceView.performDrawFinished(SurfaceView.java:304)
        at android.view.SurfaceView.lambda$onDrawFinished$0(SurfaceView.java:881)
        at android.view.-$$Lambda$SurfaceView$Cs7TGTdA1lXf9qW8VOJAfEsMjdk.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
2020-03-20 15:48:54.161 21901-21901/com.example.rongcloud_im_plugin_example E/[RC:L-crash_main_trb-F]: {"ptid":"21901-1*","stack":"java.lang.RuntimeException: Unbalanced drawPending/pendingDrawFinished calls\\n\tat android.view.ViewRootImpl.pendingDrawFinished(ViewRootImpl.java:3303)\\n\tat android.view.SurfaceView.notifyDrawFinished(SurfaceView.java:317)\\n\tat android.view.SurfaceView.performDrawFinished(SurfaceView.java:304)\\n\tat android.view.SurfaceView.lambda$onDrawFinished$0(SurfaceView.java:881)\\n\tat android.view.-$$Lambda$SurfaceView$Cs7TGTdA1lXf9qW8VOJAfEsMjdk.run(Unknown Source:2)\\n\tat android.os.Handler.handleCallback(Handler.java:891)\\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\\n\tat android.os.Looper.loop(Looper.java:207)\\n\tat android.app.ActivityThread.main(ActivityThread.java:7470)\\n\tat java.lang.reflect.Method.invoke(Native Method)\\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)\\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)\\n","reason":"java.lang.RuntimeException","env":"{\"_nonfatal\":\"true\",\"_device\":\"COL-AL10\",\"_os\":\"Android\",\"_os_version\":\"9\",\"_resolution\":\"1080x2190\",\"_app_version\":\"1.0\",\"_manufacture\":\"HUAWEI\",\"_cpu\":\"arm64-v8a\",\"_opengl\":\"3\",\"_ram_current\":\"4083\",\"_ram_total\":\"5691\",\"_disk_current\":\"3344\",\"_disk_total\":\"3486\",\"_bat\":\"100.0\",\"_run\":\"18\",\"_orientation\":\"Portrait\",\"_root\":\"false\",\"_online\":\"true\",\"_muted\":\"true\",\"_background\":\"false\"}"}

**Comment by 415593725** [comment]
我这边华为mate30和小米mix2s 也出现这个问题
