### ISSUE TITLE
AmapSearch 解析地址异常

### ISSUE THREAD

**Issue by apegeek** [fluttify-project/amap_map_fluttify#201]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
[        ] E/flutter (25277): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] E/flutter (25277): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[        ] E/flutter (25277): <asynchronous suspension>
[        ] E/flutter (25277): #2      com_amap_api_services_geocoder_RegeocodeResult.getRegeocodeAddress (package:amap_search_fluttify/src/android/com/amap/api/services/geocoder/RegeocodeResult.g.dart:102:73)
[        ] E/flutter (25277): #3      _AndroidSearchListener.onRegeocodeSearched (package:amap_search_fluttify/src/dart/amap_search.dart:1094:31)
[        ] E/flutter (25277): #4      com_amap_api_services_geocoder_GeocodeSearch.setOnGeocodeSearchListener.<anonymous closure> (package:amap_search_fluttify/src/android/com/amap/api/services/geocoder/GeocodeSearch.g.dart:121:21)
[        ] E/flutter (25277): #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
[        ] E/flutter (25277): #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
[        ] E/flutter (25277): #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
[        ] E/flutter (25277): #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
[        ] E/flutter (25277): #9      _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter (25277): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter (25277): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] E/flutter (25277): #12     _invoke3 (dart:ui/hooks.dart:302:10)
[        ] E/flutter (25277): #13     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)

**Comment by apegeek** [comment]
有人遇到吗
