### ISSUE TITLE
第一次接入，android和flutter混编，地图不显示

### ISSUE THREAD

**Issue by fengqingxiuyi** [fluttify-project/amap_map_fluttify#296]
**插件版本**
0.25.1
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
地图不显示
**复现步骤**
1. 初始化
```dart
import 'package:amap_map_fluttify/amap_map_fluttify.dart';
Future<void> main() async {
  runApp(MyApp());

  await enableFluttifyLog(false);
  await AmapService.instance.init(
    iosKey: '7a04506d15fdb7585707f7091d715ef4',
    androidKey: '7c9daac55e90a439f7b4304b465297fa',
  );
}
```
2. 创建map.dart
```dart
import 'package:amap_map_fluttify/amap_map_fluttify.dart';
import 'package:flutter/material.dart';

class MapScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Map页面')),
      body: AmapView(),
    );
  }
}
```
3. 启动android项目，通过FlutterBoost启动flutter的map页面，但是地图不显示，并且有错误日志输出
```
//省略其他日志
2020-09-06 23:54:57.774 20447-20490/com.example.flutterandroid E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: me.yohom/com.amap.api.maps.TextureMapView
        at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:91)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:356)
        at android.os.Looper.loop(Looper.java:138)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
    , null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
    #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
    #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
    #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
    #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
    #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #10     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:555:15)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #12     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
    #13     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
    #14     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
    #15     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
    #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
    #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
    #20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1247:11)
    #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #30     RenderProxyBoxMixin.perfo
2020-09-06 23:54:58.416 634-1094/? E/libnav: CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
//省略其他日志
```
4. 返回上一页面也会报错：
```
2020-09-07 00:01:33.421 20447-20490/com.example.flutterandroid E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'release__' was called on null.
    Receiver: null
    Tried calling: release__()
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    #1      _com_amap_api_maps_TextureMapView_AndroidState.dispose.<anonymous closure> (package:amap_map_fluttify/src/android/platformview/TextureMapView.g.dart:68:50)
    #2      _rootRunUnary (dart:async/zone.dart:1134:38)
    #3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #4      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
    #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
    #6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
    #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
    #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
    #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
    #10     _AmapViewState._onPlatformViewDispose (package:amap_map_fluttify/src/facade/amap_view.widget.dart)
    <asynchronous suspension>
    #11     _com_amap_api_maps_TextureMapView_AndroidState.dispose (package:amap_map_fluttify/src/android/platformview/TextureMapView.g.dart:68:14)
    #12     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4541:12)
    #13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1845:13)
    #14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #15     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5667:16)
    #16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #30     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5667:16)
    #31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #40     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #41     _InactiveE
2020-09-07 00:01:33.445 20447-20490/com.example.flutterandroid E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method PlatformService::release_batch on channel com.fluttify/foundation_method)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #2      Ref_Batch.release_batch (package:foundation_fluttify/src/type/core/ref.dart:100:27)
    #3      releaseAmapObjectPool (package:amap_map_fluttify/src/facade/amap_view.widget.dart:31:8)
    #4      _AmapViewState.dispose (package:amap_map_fluttify/src/facade/amap_view.widget.dart:252:29)
    #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4541:12)
    #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1845:13)
    #7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5667:16)
    #18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #29     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5563:14)
    #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5563:14)
    #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1841:13)
    #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1843:7)
    #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4378:14)
    #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.
2020-09-07 00:01:33.674 634-1094/? E/libnav: CablComputeBacklightLevel(): UpdateType = DifferentSceneUpdate
```
**期望行为**
地图显示
**截图**
![image](https://user-images.githubusercontent.com/20492527/92342136-74c46000-f0f2-11ea-9e40-5e4b34988982.png)

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.14.6, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by fengqingxiuyi** [comment]
已解决，我断点发现拿到的数据是百度地图的数据（因为我这个项目之前集成的是百度地图，后来才换成这个库的），然后重启手机就好了。
