### ISSUE TITLE
在地图添加Marker的时候出现Bug

### ISSUE THREAD

**Issue by sm9i** [fluttify-project/amap_map_fluttify#330]
**插件版本**
0.3.01

**遇到bug的平台(Android/iOS)**
Android(ios还没测)
**描述bug**
在给地图添加Marker的时候出现 `NoSuchMethodError: The method 'findRenderObject' was called on null.`

**复现步骤**
```dart

final AssetImage iconMapAddress = const AssetImage('assets/icons/icon_map_address.png');
final AssetImage iconMapCar = const AssetImage('assets/icons/icon_map_car.png');
final AssetImage iconMapPerson = const AssetImage('assets/icons/icon_map_person.png');

...

final MarkerOption markerOption = MarkerOption(
  coordinate: LatLng(vehicle?.lat ?? vehicle?.lat, vehicle?.lon ?? vehicle?.longitude),
  widget: MapTipWidget(
    asset: iconMapCar,
    title: '车辆',
    address: navigator?.vehicleNo ?? '',
  ),
  infoWindowEnabled: false,
  anchorV: 1,
);
amapController.addMarker(markerOption);

...

final MarkerOption markerOption = MarkerOption(
  coordinate: latLng,
  widget: MapTipWidget(
    asset: iconMapAddress,
    title: isTake ? '发货地' : '卸货地',
    address: address?.district ?? '',
  ),
  infoWindowEnabled: false,
  anchorV: 1,
);
amapController.addMarker(markerOption);

```
**期望行为**

**截图**

```error
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _AmapViewState.widgetToImageData.<anonymous closure> (package:amap_map_fluttify/src/facade/amap_view.widget.dart:286:31)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
#4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#5      _rootRun (dart:async/zone.dart:1190:13)
#6      _CustomZone.run (dart:async/zone.dart:1093:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#8      _invoke (dart:ui/hooks.dart:251:10)
#9      _drawFrame (dart:ui/hooks.dart:209:3)
```

**flutter doctor**

```shell
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H15 darwin-x64,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
[✓] VS Code (version 1.54.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.


```

问题就是这样，如果去掉一个的话会正常运行，我想可能是我自定义的Widget`MapTipWidget`的问题，但是试过不怎么行，比如当我给了Key之后还是这个问题。

**Comment by sm9i** [comment]
解决掉了。可能是因为addMarker都是async的问题。在controller.addMarker加await 就ok了，打扰了。
