### ISSUE TITLE
Android虚拟导航栏显示和隐藏切换，地图显示白板问题和APP闪退现象

### ISSUE THREAD

**Issue by loaderman** [fluttify-project/amap_map_fluttify#87]
1.在android5.1版本的手机上，切换手机系统虚拟导航栏显示和隐藏的时候，图层会出现白板现象
2.在android8.0版本手机上，切换手机系统虚拟导航栏显示和隐藏的时候，图层没有白板现象，但是切换手机系统虚拟导航栏显示和隐藏后，再移动图层，会卡死并且闪退APP
flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.AbstractMethodError: abstract method "void io.flutter.plugin.platform.PlatformView.onInputConnectionLocked()"
        at io.flutter.plugin.platform.VirtualDisplayController.onInputConnectionLocked(VirtualDisplayController.java:166)
        at io.flutter.plugin.platform.PlatformViewsController.lockInputConnection(PlatformViewsController.java:370)
        at io.flutter.plugin.platform.PlatformViewsController.access$1000(PlatformViewsController.java:36)
        at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:165)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:120)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:57)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
/ActivityManager: am_pause_activity call stack
    java.lang.RuntimeException: Here is not exception,only print call stack
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:839)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2760)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2617)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2552)
        at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11704)
        at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11601)
        at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12285)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11796)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
ActivityManager: am_resume_activity call stack
    java.lang.RuntimeException: Here is not exception,only print call stack
        at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:1853)
        at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1478)
        at com.android.server.am.ActivityStackSupervisor.resumeTopActivitiesLocked(ActivityStackSupervisor.java:2528)
        at com.android.server.am.ActivityStackSupervisor.resumeTopActivitiesLocked(ActivityStackSupervisor.java:2517)
        at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:4592)
        at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:4732)
        at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1236)
        at android.os.BinderProxy.sendDeathNotice(Binder.java:551)

**Comment by yohom** [comment]
看这个log，应该是`PlatformView`的bug，建议去flutter官方提issue。
